import { useEffect, useState } from 'react'
import { ArrowUpRight, CalendarDays, CheckCircle2, CircleDollarSign, Star, Users } from 'lucide-react'
import { getVendorDashboard } from '../api/dashboardService'

const experiences = [['Bãi Bắc - Cây Đa', '48', '8.200.000 ₫', '4.9'], ['Đỉnh Bàn Cờ', '35', '5.100.000 ₫', '4.8'], ['Ghềnh Bàng', '25', '3.400.000 ₫', '4.7']]
const bookings = [['#BK1024', 'Nguyễn Minh', 'Bãi Bắc - Cây Đa', '18/09/2026', '2 guests', '450.000 ₫']]
export default function VendorDashboardPage() {
  const [data, setData] = useState(null)
  useEffect(() => { getVendorDashboard().then(setData) }, [])
  if (!data) return <div className="state-card">Đang tải dashboard...</div>
  const metrics = [{ label: 'Tổng doanh thu', value: data.revenue, note: '↑ 12.5% so với tháng trước', icon: CircleDollarSign }, { label: 'Doanh thu tháng này', value: data.monthlyRevenue, note: '↑ 8.2% so với tháng trước', icon: ArrowUpRight }, { label: 'Tổng Booking', value: data.bookings, note: '↑18 tháng này', icon: CalendarDays }, { label: 'Đánh giá', value: data.rating, note: `${data.reviews} đánh giá`, icon: Star }]
  return <div className="vendor-dashboard"><div className="dashboard-welcome"><div><h1>Chào buổi sáng, Sơn Trà Trekking 👋</h1><p>Đây là tình hình hoạt động của doanh nghiệp hôm nay.</p></div></div><div className="metric-grid">{metrics.map(({ label, value, note, icon: Icon }) => <div className="metric-card" key={label}><div className="metric-card__label">{label}<Icon size={15} /></div><strong>{value}</strong><span>{note}</span></div>)}</div><div className="dashboard-chart-grid"><section className="dashboard-card revenue-chart"><div className="card-heading"><h2>Doanh thu</h2><div className="periods"><button>7 ngày</button><button>30 ngày</button><button className="selected">3 tháng</button><button>12 tháng</button></div></div><div className="line-chart"><div className="chart-line" /><div className="chart-points"><i /><i /><i /><i /></div><div className="chart-labels"><span>Th06 ·<br />4.2M</span><span>Th07 ·<br />5.8M</span><span>Th08 ·<br />6.4M</span><span>Th09 ·<br />7.25M</span></div></div></section><section className="dashboard-card booking-chart"><h2>Tổng quan đơn đặt</h2><div className="chart-legend"><span><i />Xác nhận</span><span><i />Hoàn thành</span><span><i />Hủy đơn</span></div><div className="bar-chart"><div><b>4</b><i style={{ height: '76%' }} /><span>Xác<br />nhận</span></div><div><b>11</b><i style={{ height: '100%' }} /><span>Hoàn<br />thành</span></div><div><b>8</b><i className="danger" style={{ height: '32%' }} /><span>Hủy<br />đơn</span></div></div></section></div><section className="dashboard-card table-card"><h2>Hiệu suất trải nghiệm</h2><div className="responsive-table"><table><thead><tr><th>Trải nghiệm</th><th>Đơn đặt</th><th>Doanh thu</th><th>Đánh giá</th><th>Trạng thái</th></tr></thead><tbody>{experiences.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}<td><span className="status-pill"><CheckCircle2 size={12} /> Đang hoạt động</span></td></tr>)}</tbody></table></div></section><section className="dashboard-card table-card"><div className="card-heading"><h2>Tour đặt gần đây</h2><a href="#bookings">Xem tất cả</a></div><div className="responsive-table"><table><thead><tr>{['ID tour', 'Khách hàng', 'Trải nghiệm', 'Ngày', 'Số khách', 'Thành tiền', 'Trạng thái', 'Hành động'].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{bookings.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}<td><span className="status-pill">Xác nhận</span></td><td><a href="#booking">Xem</a></td></tr>)}</tbody></table></div></section><section className="dashboard-card quick-actions"><h2>Thao tác nhanh</h2><div><button className="primary-action">+ Tạo trải nghiệm</button><button>+ Tạo tuyến</button><button>Xem Booking</button><button>Đề xuất Reward</button></div></section></div>
}
