import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Button, Input } from '../components/ui'
import { AuthPage } from './AuthPage'

const icon = (name) => <img src={`/assets/figma/icon-${name}.svg`} alt="" />

export function RegisterPage() {
  const [values, setValues] = useState({ fullName: '', email: '', phone: '', password: '', confirmPassword: '', agreed: false })
  const [errors, setErrors] = useState({})
  const [payload, setPayload] = useState(null)
  const change = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }))
  const submit = (event) => { event.preventDefault(); const next = {}; if (!values.fullName.trim()) next.fullName = 'Vui lòng nhập họ và tên.'; if (!/^\S+@\S+\.\S+$/.test(values.email)) next.email = 'Vui lòng nhập email hợp lệ.'; if (!values.phone.trim()) next.phone = 'Vui lòng nhập số điện thoại.'; if (values.password.length < 8) next.password = 'Mật khẩu cần có ít nhất 8 ký tự.'; if (values.confirmPassword !== values.password) next.confirmPassword = 'Mật khẩu xác nhận chưa khớp.'; if (!values.agreed) next.agreed = 'Bạn cần đồng ý với điều khoản dịch vụ.'; setErrors(next); if (Object.keys(next).length) return; const body = { full_name: values.fullName.trim(), email: values.email.trim(), phone: values.phone.trim(), password: values.password }; setPayload(body); console.info('DRF registration payload', body) }
  return <AuthPage variant="register" title="Trải nghiệm Thiên Nhiên Đích Thực" description="Đăng ký tài khoản thành viên Sơn Trà RESort để nhận ưu đãi 15% cho kỳ nghỉ đầu tiên." alternateText="Đã có tài khoản?" alternateLink="/login" alternateLabel="Đăng nhập ngay"><form className="auth-form" onSubmit={submit} noValidate><Input label="Họ và tên" name="fullName" value={values.fullName} onChange={change} autoComplete="name" error={errors.fullName} placeholder="Nguyễn Văn A" leadingIcon={icon('user')} /><Input label="Email" name="email" type="email" value={values.email} onChange={change} autoComplete="email" error={errors.email} placeholder="nguyenvana@email.com" leadingIcon={icon('mail')} /><Input label="Số điện thoại" name="phone" type="tel" value={values.phone} onChange={change} autoComplete="tel" error={errors.phone} placeholder="090 1234 567" leadingIcon={icon('phone')} /><Input label="Mật khẩu" name="password" type="password" value={values.password} onChange={change} autoComplete="new-password" error={errors.password} placeholder="••••••••" leadingIcon={icon('lock')} trailingIcon={icon('eye')} /><Input label="Xác nhận mật khẩu" name="confirmPassword" type="password" value={values.confirmPassword} onChange={change} autoComplete="new-password" error={errors.confirmPassword} placeholder="••••••••" leadingIcon={icon('lock')} trailingIcon={icon('eye')} /><label className={`terms-check ${errors.agreed ? 'terms-check--error' : ''}`}><input name="agreed" type="checkbox" checked={values.agreed} onChange={change} /><span aria-hidden="true" />Tôi đồng ý với <a href="#terms">Điều khoản dịch vụ</a> &amp; <a href="#privacy">Chính sách bảo mật</a></label>{errors.agreed && <p className="terms-error">{errors.agreed}</p>}<Button type="submit" size="lg">Đăng ký thành viên</Button><div className="auth-divider"><span />hoặc đăng ký bằng<span /></div><div className="auth-social"><Button variant="secondary" type="button" className="auth-social__button"><span aria-hidden="true">○</span> Google</Button><Button variant="secondary" type="button" className="auth-social__button"><span aria-hidden="true">□</span> Facebook</Button></div>{payload && <output className="auth-payload">DRF payload: {JSON.stringify(payload)}</output>}</form><p className="auth-card__footer">Đã có tài khoản? <Link to="/login">Đăng nhập ngay</Link></p></AuthPage>
}
